GET http://localhost:3001/api/todos

###
POST http://localhost:3001/api/todos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IktkZXYiLCJpZCI6IjY5N2Y4MDhlMjAyN2ZiNmJkZTI3MmNlMiIsImlhdCI6MTc3MDA4ODQ5MX0.u0vgAitYl8lfq3Rczmxuac-gCUvh8tp8drw0UACoDlg

{
  "title": "Do homework",
  "completed": true
}
###
PUT http://localhost:3001/api/todos/697cdba4e6333a9b89738fb2
Content-Type: application/json

{
  "title": "Do yoga",
  "completed": false,
}
###
DELETE http://localhost:3001/api/todos

###
GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "Kdev",
  "name": "Khoi",
  "password": "123456"
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "Kdev",
  "password": "123456"
}