GET http://localhost:3001/api/todos

###
POST http://localhost:3001/api/todos
Content-Type: application/json

{
  "title": "Do homework",
  "completed": true
}
###
PUT http://localhost:3001/api/todos/697cdba4e6333a9b89738fb2
Content-Type: application/json

{
  "title": "Do yoga",
  "completed": false
}
###
DELETE http://localhost:3001/api/todos